[package]
name = "aoc-2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc-framework = {git = "https://github.com/etwyniel/aoc-framework"}
fxhash = "0.2.1"
itertools = "0.10.5"
